### ISSUE TITLE
Cannot set throttle?

### ISSUE THREAD

**Issue by ldaug99** [brhannan/sl-ksp#1]
The in-game throttle does not responde to changes to the throttle in the Simulink model. Throttle in-game is always set to 1 when autopilot is enegaged. When autopilot is off, the in-game throttle is always 0 regardsless of the throttle value in the simulink model.

![v1 0_throttle_not_updating_in-game](https://user-images.githubusercontent.com/34159442/115114247-8cb86800-9f8e-11eb-95c8-6d95b1117e33.PNG)

Is there any way to control the throttle? I'd like to control the throttle, so that I can make the rocket hover?

The problem described above occured in the version 1.0 of the toolbox. If I use your version 1.1 of the toolbox, the in-game throttle does not chance at all when autopilot is enegage and regardless of the simulink throttel value.

![v1 1_no_throttel_at_all](https://user-images.githubusercontent.com/34159442/115114253-95a93980-9f8e-11eb-9b32-58f86a1b8995.PNG)

**Comment by brhannan** [comment]
Thanks. This has been fixed. The latest release (pushed today 4/18) allows throttle control.

**Comment by ldaug99** [comment]
Can confirm. It works like a charm! Thank you very much. Very cool project by the way!
